### ISSUE TITLE
dataset1/cam2.zip is corrupt

### ISSUE THREAD

**Issue by evroon** [CenekAlbl/drone-tracking-datasets#1]
Thank you for making this dataset openly available.

I noticed one mistake: there is something wrong with [dataset1/cam2.zip](https://github.com/CenekAlbl/drone-tracking-datasets/blob/master/dataset1/cam2/cam2.zip). I downloaded it twice to be sure, but I get the following error when using the `unzip` command on Ubuntu 20.04:

```Archive:  cam2.zip
warning [cam2.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4
```

**Comment by evroon** [comment]
Nevermind, unpacking using 7zip with the `unpack.sh` script does work, so it is just a discrepency between archiving programs.

**Comment by CenekAlbl** [comment]
Yes, I noticed that it doesn't work with unzip (very weird issue) only after uploading it and did not want to re-upload everything so I added the script to unpack it using 7zip. Glad to hear you figured it out!
